trigger:
- main

pool:
  name: 'Agent_Pool'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm init -y
    npm install express --save
    npm run build
  displayName: 'npm install and build'
